(define (main args)
  (if (not (list? args))
      'Arguments to main must be in a list'
      (
       (display (list_sumr args))
       (newline)
       (display (insert_last 'value args))
       (newline)
       (display (remove_last args))
       (newline)
       (display (list_reverse args))
       (newline)
       (display (insert_last 'value (list_reverse args)))
       (newline)
       (display (list_reverse (insert_last 'value args)))
       (newline)
       )
      )
  )
