(define (function a)
	l
	5
	(if x y n)
	(if a n p)
	(cadr '(a bb cc))
	(cons 'a '((x y) beta))
	(and 4 5)
	(or 7 8)
	(not '(ab))
	(number? 'ab)
	(symbol? (cons '5678 '()))
	(and (list? 87) (cons '765 '(e n 6 5 4)))
	(zero? '())
	(null? '(if a b c))
	(or (and (char? 55) (char? '())) (char? 'd))
	(string? 'uytrewqsdwefgrhtyj7htgrfe)
	(+ 5 'g)
	(- 55 '(d))
	(- 55 '(45))
	;(/ a 6)
)